theme: jekyll-theme-minimal
title: SPARSH SHARMA
description: "Smiling like I just solved turbulence... but secretly wondering if anyone noticed my hands shaking. 🎓 #PhDDefenseDay #17.12.2019"
logo: /d-dayCopy.jpg
logo2: /download (4).png
